### ISSUE TITLE
fpgabist fails to pass the proper device enumeration for fpgadiag

### ISSUE THREAD

**Issue by GrueMaster** [OPAE/opae-sdk#1090]
When running 

> fpgabist  /opt/intelrtestack/a10_gx_pac_ias_1_2_pv/hw/samples/nlb_mode_3/bin/nlb_mode_3.gbs

fpgadiag will fail read/write/trput tests with 

> Error: device enumeration failed.

This is because of an improperly formatted command line for fpgadiag.  The current mode is trying to run with '-B 86', but fpgadiag requires '-B 0x86'.

Example:
fpgabist generated command:
`fpgadiag -B 86 --mode=read --read-vc=vh0 --write-vc=vh0 --multi-cl=4 --begin=1024, --end=1024 --timeout-sec=5 --cont`

Proper command:
`fpgadiag -B 0x86 --mode=read --read-vc=vh0 --write-vc=vh0 --multi-cl=4 --begin=1024, --end=1024 --timeout-sec=5 --cont`

**Comment by tswhison** [comment]
Closed as fixed.
