### ISSUE TITLE
Missing curly braces in threshold.c in plugins directory

### ISSUE THREAD

**Issue by haoyouab** [OPAE/opae-sdk#1183]
I get this error and it says there is a misleading indentation:

/opae-sdk/libopae/plugins/xfpga/metrics/threshold.c: In function ‘get_bmc_threshold_info’:
/opae-sdk/libopae/plugins/xfpga/metrics/threshold.c:169:2: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
  if (_handle->bmc_handle == NULL)
  ^~
/opae-sdk/libopae/plugins/xfpga/metrics/threshold.c:171:3: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
   if (!_handle->bmc_handle) {
   ^~

If I'm understanding the code in the right way, a pair of curly braces are missing along with the first 'if' clause?

**Comment by anandaravuri** [comment]
Fixed
