### ISSUE TITLE
Unable to locate necessary files for building the simulator

### ISSUE THREAD

**Issue by ShashankMG123** [OPAE/opae-sdk#1307]
I'm unable to locate the file opae-1.3.0.2.x86_64-ase.deb to use the OPAE in the simulation environment.

**Comment by nakulkorde** [comment]
Hi @ShashankMG123 , you can find the released installation packages here: https://github.com/OPAE/opae-sdk/releases.

Please close the issue if you are satisfied by the response or feel free to add to it if you need help.

**Comment by ShashankMG123** [comment]
@nakulkorde Thanks for the release. On the quick start guide to install OPAE it specifics a file named 'opae-<release>.x86_64-ase.deb' which needs to be installed in order to use OPAE in a simulated environment. Assuming the release to be 1.3.0-2 the file needed would be ' opae-1.3.0-2.x86_64-ase.deb ' which is not found on the release page.
