### ISSUE TITLE
Example intg_xeon_nlb instantiation error.

### ISSUE THREAD

**Issue by ShashankMG123** [OPAE/opae-sdk#1328]
Hey,
I've been trying to run the intg_xeon_nlb example shipped with the opae-sdk. During the 'make sim' command I came across three errors all of which were instantiation errors stating that the respective design units were not found.
I have attached a screenshot of my error.
Thank you. 
https://user-images.githubusercontent.com/37444395/61383284-01e39e80-a8cc-11e9-8de8-bd63be02b28c.png

**Comment by michael-adler** [comment]
Sorry, I keep trying to get some of those ancient samples deleted. For reasons I don't completely understand they keep being resurrected.

I assume you are just looking for sample workloads to get started. Please use the tutorial at https://github.com/OPAE/intel-fpga-bbb/tree/master/samples.
