### ISSUE TITLE
No way to install drivers from git source.

### ISSUE THREAD

**Issue by GrueMaster** [OPAE/opae-sdk#1352]
Currently, there is no way to build the driver packages from sources downloaded here, and the drivers are only included with published releases.  For example, how do we build/install drivers for the 1.1.4 release for the D5005 PAC kit?

**Comment by tswhison** [comment]
Thanks for your post.  We will look into making the driver source available.  Until that time, please use the [downloads portal](https://www.intel.com/content/www/us/en/programmable/solutions/acceleration-hub/downloads.html).

**Comment by tswhison** [comment]
We have made a kernel tree complete with the drivers available here: https://github.com/OPAE/linux-dfl
