### ISSUE TITLE
D5005 doesn't show up on PCIe

### ISSUE THREAD

**Issue by sidsahay** [OPAE/opae-sdk#1754]
I can't seem to get one of our D5005s to show up on PCIe or `fpgainfo` regardless of the configuration/system I try it in. The 12V power LED is on, but the Power Good LED and the AFU LEDs are always off i.e. only one orange LED is on when the machine boots up. 

We know the machine supports the card because it works fine with a different D5005, which has 12V power, power good, and done LEDs light up when it boots and it works fine with the FPGA tools and OPAE, so we suspect there's something wrong with this particular card. Any ideas what could be the issue? I would have tried reflashing the BMC but can't since the card doesn't show up in the system.

**Comment by GrueMaster** [comment]
If the card doesn't show up in lspci, this is not a software issue.  You should contact your sales rep or customer support to see about having that card serviced.

**Comment by sidsahay** [comment]
Thanks, will do.
