### ISSUE TITLE
build rpm package failed on tag/2.0.1-2

### ISSUE THREAD

**Issue by flaging** [OPAE/opae-sdk#1781]
I'm building a rpm package. however i can't get the proper method, so i use the method provided by 2.0.0 in doc https://opae.github.io/2.0.0/docs/install_guide/installation_guide.html

it works fine when i compile 2.0.0, but when it comes to 2.0.1-2,  package build failed with the follow errors:

```
error: File not found: /home/opae-sdk/build/_CPack_Packages/Linux/RPM/opae-2.0.1-2.x86_64/usr/bin/opaevfiotest

error: File not found by glob: /home/opae-sdk/build/_CPack_Packages/Linux/RPM/opae-2.0.1-2.x86_64/usr/lib64/libopaevfio.so*
```

i wonder if there is any changes make this error happen , and how should i change config files to make it works??

Thanks in advance!!!

**Comment by tswhison** [comment]
Hi @flaging, thanks for your question.  For the vfio library, there is a check in the build system as to whether linux/vfio.h is present and at the appropriate level.  Can you try adding the kernel headers, and then recreating the RPM?  I think this will solve the issue.
