### ISSUE TITLE
Can't install PACSign. 

### ISSUE THREAD

**Issue by saitej25** [OPAE/opae-sdk#1898]
How can I install this utility on Ubuntu?

**Comment by saitej25** [comment]
Tried 
cd opae-sdk/python/pacsign/
python3 ./setup.py build
python3 ./setup.py install

**Comment by chrbirks** [comment]
That method has worked for me before except for running the last install command with sudo. But it's hard to say without any error messages.

**Comment by r-rojo** [comment]
Like @chrbirks said, it's hard to know what could be wrong without more information, like error messages.
Can you provide which Ubuntu distro you're trying this on as well as the Python version?
It could be that your user does not have sufficient privileges to install files into that Python instance.
You could also use "python3 -m pip install <path to PACSign>  --user" to install it into your user's Python site-packages directory.

**Comment by saitej25** [comment]
works with sudo
