### ISSUE TITLE
Rename instances of `iova`

### ISSUE THREAD

**Issue by luebbers** [OPAE/opae-sdk#236]
Several instances in libopae-c (and the samples) still refer to "IO Virtual Addresses" (`iova`). This can be confusing on platforms that do not have an IOMMU enables (here, these addresses are physical addresses).

It may be a good idea to rename these usages to something more resembling an "IO address", which, depending on platform configuration, can be host physical, guest physical, or potentially even virtual (who knows?).

**Comment by tswhison** [comment]
Implemented - closing
