### ISSUE TITLE
OPAE-Intel FPGA Drivers

### ISSUE THREAD

**Issue by knmurth** [OPAE/opae-sdk#2493]
Hi, I require newest version for OPAE-Intel FPGA Drivers.Are they available,if so please share

**Comment by rweight** [comment]
The intel-fpga drivers are legacy. We have been actively working on upstreaming the drivers under the name of "Device Feature List" (DFL). You have a couple of options to get the latest driver:

(1) You can harvest the latest patches from this branch, or just build this branch and use the kernel:
https://github.com/OPAE/linux-dfl/tree/fpga-ofs-dev-5.15-lts
For more information, see the wiki: https://github.com/OPAE/linux-dfl/wiki

(2) There is a community effort to build an out-of-tree driver with patches from the above repo. You can find it here:
https://github.com/OPAE/linux-dfl-backport/tree/base/fpga-ofs-dev-5.15-lts

I'm not sure which branch to recommend. The most active are probably the n5010/fpga-ofs-dev-5.1*-lts and rhel*/fpga-ofs-dev-5.1*-lts branches. Note that we just transitioned recently from the 5.10-lts to the 5.15-lts, and our development focus is now on 5.15-lts.
