### ISSUE TITLE
OPAE-Intel FPGA drivers

### ISSUE THREAD

**Issue by knmurth** [OPAE/opae-sdk#2494]
Hi all,
I am trying to compile OPAE-Intel FPGA drivers,but compilation is getting terminated and resulting in the below error
opae-intel-fpga-driver-2.0.1/drivers/i2c/busses/i2c-altera.c:636:4: error: implicit declaration of function ‘i2c_new_device’; did you mean ‘i2c_acpi_new_device’? [-Werror=implicit-function-declaration]
  636 |    i2c_new_device(&idev->adapter, pdata->devices + i);
      |    ^~~~~~~~~~~~~~
      |    i2c_acpi_new_device
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:281: /home/kn/opae-intel-fpga-driver-2.0.1/drivers/i2c/busses/i2c-altera.o] Error 1
make[1]: *** [Makefile:1879: /home/kn/opae-intel-fpga-driver-2.0.1] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.13.0-28-generic'
make: *** [Makefile:92: all] Error 2
Can anyone suggest suitable modifications

**Comment by rweight** [comment]
The opae-intel-fpga-driver is the legacy driver and was primarily supported on the RHEL7 kernels. It was never ported to 5.15.

We have been actively working on upstreaming the drivers under the name of "Device Feature List" (DFL). Take a look at:

https://github.com/OPAE/linux-dfl/tree/fpga-ofs-dev-5.15-lts
https://github.com/OPAE/linux-dfl/wiki
https://github.com/OPAE/linux-dfl-backport/tree/base/fpga-ofs-dev-5.15-lts
