### ISSUE TITLE
Some errors when compiling OPAE-Intel FPGA Drivers

### ISSUE THREAD

**Issue by knmurth** [OPAE/opae-sdk#2512]
Attempting on Ubuntu 20.04
Facing the below error in make file,kindly suggest solution
make[1]: Entering directory '/usr/src/linux-headers-5.13.0-30-generic'
  CC [M]  /home/kn/opae-intel-fpga-driver-0.9.0/drivers/fpga/fpga-mgr.o
  LD [M]  /home/kn/opae-intel-fpga-driver-0.9.0/fpga-mgr-mod.o
  CC [M]  /home/kn/opae-intel-fpga-driver-0.9.0/drivers/fpga/intel/uuid_mod.o
/home/kn/opae-intel-fpga-driver-0.9.0/drivers/fpga/intel/uuid_mod.c:57:18: error: unknown type name ‘uuid_be’; did you mean ‘uuid_le’?
   57 | void uuid_be_gen(uuid_be *bu)
      |                  ^~~~~~~
      |                  uuid_le
/home/kn/opae-intel-fpga-driver-0.9.0/drivers/fpga/intel/uuid_mod.c:104:38: error: unknown type name ‘uuid_be’; did you mean ‘uuid_le’?
  104 | int uuid_be_to_bin(const char *uuid, uuid_be *u)
      |                                      ^~~~~~~
      |                                      uuid_le
make[2]: *** [scripts/Makefile.build:281: /home/kn/opae-intel-fpga-driver-0.9.0/drivers/fpga/intel/uuid_mod.o] Error 1
make[1]: *** [Makefile:1879: /home/kn/opae-intel-fpga-driver-0.9.0] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.13.0-30-generic'
make: *** [Makefile:38: all] Error 2

**Comment by tswhison** [comment]
As mentioned in issue #2494, the opae-intel-fpga driver is no longer supported.  Please use the latest DFL driver instead.
