### ISSUE TITLE
Errors while compiling OPAE-Intel-FPGA Drivers

### ISSUE THREAD

**Issue by knmurth** [OPAE/opae-sdk#2513]
Attempting on Ubuntu-21.10 LTS
Facing the below errors,kindly suggest any solution
/home/kn/opae-intel-fpga-driver-0.9.0/drivers/fpga/intel/fme-pr.c:326:28: error: macro "access_ok" passed 3 arguments, but takes just 2
  326 |         port_pr.buffer_size))
      |                            ^
In file included from ./include/linux/uaccess.h:11,
                 from /home/kn/opae-intel-fpga-driver-0.9.0/drivers/fpga/intel/fme-pr.c:25:
./arch/x86/include/asm/uaccess.h:69: note: macro "access_ok" defined here
   69 | #define access_ok(addr, size)     \
      | 
/home/kn/opae-intel-fpga-driver-0.9.0/drivers/fpga/intel/fme-pr.c:325:7: error: ‘access_ok’ undeclared (first use in this function)
  325 |  if (!access_ok(VERIFY_READ, port_pr.buffer_address,
      |       ^~~~~~~~~
/home/kn/opae-intel-fpga-driver-0.9.0/drivers/fpga/intel/fme-pr.c:325:7: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:281: /home/kn/opae-intel-fpga-driver-0.9.0/drivers/fpga/intel/fme-pr.o] Error 1
make[1]: *** [Makefile:1879: /home/kn/opae-intel-fpga-driver-0.9.0] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.13.0-30-generic'
make: *** [Makefile:38: all] Error 2

**Comment by tswhison** [comment]
As mentioned in issue #2494, the opae-intel-fpga driver is no longer supported. Please use the latest DFL driver instead.
