### ISSUE TITLE
Build CI does not check -DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by chipb** [OPAE/opae-sdk#252]
Issue fixed by #250 would have been caught pre-merge if we were build checking both "Debug" and "Release" modes. Any opposition to just doing both?

If we want to limit to a single mode, I'd argue we want "Release" to be that mode.

**Comment by nakulkorde** [comment]
Does this need to be addressed before the next release?

**Comment by chipb** [comment]
No, I don't think it's pressing, but it's also not a huge change either...I meant to just send a PR but had forgotten about it.

Are you planning significant changes to the CI flow that'll negate a change anyway?

**Comment by nakulkorde** [comment]
@luebbers Do you think doing two builds with each build mode is fine? It will only add a few extra minutes to our per checkin process.

**Comment by tswhison** [comment]
Resolved by https://github.com/OPAE/opae-sdk/pull/461
