### ISSUE TITLE
remove `mmio_region` parameter from `handle::open`

### ISSUE THREAD

**Issue by r-rojo** [OPAE/opae-sdk#258]
* Remove `mmio_region` parameter from `handle::open`
* Add handle::map_csr which calls `fpgaMapMMIO`
```C++
uint8_t* map_csr(uint32_t csr_space)
```

**Comment by tswhison** [comment]
See https://github.com/OPAE/opae-sdk/pull/263

**Comment by r-rojo** [comment]
#266 removed the need for mapping MMIO from C++ and #271 removes the csr_space from `handle::open`
