### ISSUE TITLE
make fail by GCC 7.3.1

### ISSUE THREAD

**Issue by YouYouExcellent** [OPAE/opae-sdk#260]
I try to build 0.13 on fedora 27. but when to run command make, it says "this statement may fall through [-Werror=implicit-fallthrough=]" in opae-sdk/safe_string/mem_primitives_lib.c, I think you may add /* fall through */ under each of the end of cases.

**Comment by YouYouExcellent** [comment]
well, except this issue, there are several other make issues exist

**Comment by tswhison** [comment]
Thanks @YouYouExcellent.  These are being addressed by [259](https://github.com/OPAE/opae-sdk/pull/259)

**Comment by YouYouExcellent** [comment]
thanks!
