### ISSUE TITLE
Provide more information with fpgaconf

### ISSUE THREAD

**Issue by shivarao** [OPAE/opae-sdk#275]
Can we have fpgaconf print out some additional information?

Specifically, when we have interface ID mismatch, can it print out the expected ID (from the FIM) and the actual ID (from the AFU bitstream).

It would also be useful if it printed out the before and after AFU UUIDs (maybe with verbosity turned up).

This would really help with debugging customer issues that have a FIM / AFU mismatch.

**Comment by tswhison** [comment]
Resolved by https://github.com/OPAE/opae-sdk/pull/490
