### ISSUE TITLE
OPAE examples availability

### ISSUE THREAD

**Issue by marcomontini** [OPAE/opae-sdk#303]
Hi,
I would like to say if there's the possibility to have other examples as "hello world!" one.  I'm trying to realize a project by using OPAE and I should send data from processor to accelerator but, first of all,  I am not able to generate correctly a read request from AFU to processor. Is there any references with examples about it? Thanks 

Marco Montini

**Comment by luebbers** [comment]
@marcomontini: Do the tutorials in  https://github.com/OPAE/intel-fpga-bbb/tree/master/samples/tutorial help with this?
