### ISSUE TITLE
Memory Read request

### ISSUE THREAD

**Issue by marcomontini** [OPAE/opae-sdk#304]
Hi,
I should create a memory read request header (by using the type 't_ccip_c0_ReqMemHdr') but I do not know what values  assign to 'address' and  'mdata' fields. I have to send data from processor to AFU for processing. Can you help me? Thanks

Marco Montini

**Comment by tswhison** [comment]
@michael-adler is this something you could assist with?

**Comment by michael-adler** [comment]
You could start by looking at the tutorials at https://github.com/OPAE/intel-fpga-bbb/tree/master/samples/tutorial, which begin with generating some memory requests. The general idea is you allocate shared memory using OPAE in software on the host and then pass buffer addresses to the FPGA using CSRs (MMIO writes). Then the FPGA can generate memory requests as needed to the buffers.

**Comment by luebbers** [comment]
@marcomontini: Have you been able to make progress by looking at the tutorial? Thank you!
