### ISSUE TITLE
Does Make Install need to install documentation by default

### ISSUE THREAD

**Issue by buie1** [OPAE/opae-sdk#322]
By default do we need to install all the documentation files?
These are only needed for our Release branch

**Comment by tswhison** [comment]
Hi Jonathan, could you elaborate a bit on this one?  We're not sure we see the issue you're pointing out.

**Comment by luebbers** [comment]
Hi @buie1 - any updates?

**Comment by rlee5-intel** [comment]
No update since Apr. 26.  Closing it for now.
