### ISSUE TITLE
building OPAE: cmake phase reports fatal error, but succeeds

### ISSUE THREAD

**Issue by stgrzeszczak** [OPAE/opae-sdk#371]
Hi,

I've noticed that the cmake phase reports an error:
`fatal: Not a git repository (or any of the parent directories): .git`

Still, step is successful and the project can be built.

Reproduction:
Download [https://github.com/OPAE/opae-sdk/archive/0.13.1.tar.gz](https://github.com/OPAE/opae-sdk/archive/0.13.1.tar.gz) and install the dependencies listed in [https://opae.github.io/latest/docs/install_guide/installation_guide.html#software-requirements](https://opae.github.io/latest/docs/install_guide/installation_guide.html#software-requirements).

Then, in opae-sdk directory run:
`$ mkdir mybuild`
`$ cd mybuild`
`$ cmake .. -DBUILD_ASE=1`

**Comment by nakulkorde** [comment]
The reason for that is GitHub by itself wraps a tarball for every release and it includes some git files in the tarball. The error comes from git and can be safely ignored. I would encourage you to use the tarball that we provide with our latest release that can be found [here :](https://github.com/OPAE/opae-sdk/releases/download/1.0.0-5/opae-1.0.0.tar.gz)
