### ISSUE TITLE
1.0 release does not have c++ included

### ISSUE THREAD

**Issue by mjc0608** [OPAE/opae-sdk#407]
The 1.0 release does not have c++ included, but the code exists in the master. Is the master a stable version that we can use directly?

**Comment by r-rojo** [comment]
Hi Jachim,
The testing on the C++ API in master is mostly limited to unit/functional testing using the mock driver library. You can use it but please be aware that it has not gone thorough the same level of system/integration testing as releases do. If you do use it, we encourage you to file any issues that you may encounter while doing so.

**Comment by mjc0608** [comment]
Thanks very much!
