### ISSUE TITLE
Is the temperature measured in farenheit or celsius?

### ISSUE THREAD

**Issue by iamatrashbin** [OPAE/opae-sdk#473]
In the documentation the temperature the function `fpgainfo temp` reports is said to be in farenheit, see: [the docs](https://opae.github.io/latest/docs/fpga_tools/fpgainfo/fpgainfo.html).

However, when using the function irl the temperature is said to be printed in degrees celsius. Which of those is true, celsius of farenheit?

Thank you, in advance.

**Comment by r-rojo** [comment]
Hi @iamatrashbin ,
The temperature is actually in degrees celcius which means the documentation is incorrect.
Thanks for pointing this out.  This will be fixed in the documentation.

**Comment by r-rojo** [comment]
This has been fixed in #482

**Comment by tswhison** [comment]
Issue fixed - closing
