### ISSUE TITLE
ASE avs_bfm_inst_ddra incorrect read data valid response number

### ISSUE THREAD

**Issue by stefanstoeckigt** [OPAE/opae-sdk#579]
The avs_bfm_inst_ddra replied with the incorrect number of readdatavalid (13 instead of 14) when requesting two reads of burst size 8 and 6. 

![modelsim](https://user-images.githubusercontent.com/1832236/42869928-5f04fd34-8a6e-11e8-8d58-5b887364e4f0.png)

**Comment by tswhison** [comment]
Hi Tracy, could you have a look/provide next steps?  Thanks

**Comment by lzhan55** [comment]
I will look into it.

**Comment by lzhan55** [comment]
@stefanstoeckigt Is this a memory read? What does burst side 8 and 6 mean in your test?

**Comment by stefanstoeckigt** [comment]
@lzhan55 This is a memory read. With two burst, the first burst count of 8 (512bit Words) and then a burst count of 6 (512bit words). If you look at the readvalid signal it is only valid for 13 clock cycles instead of 14.

**Comment by lzhan55** [comment]
Our hardware team will look into it and will get back to you later.

**Comment by stefanstoeckigt** [comment]
Attached the .wlf file, navigate to the 101800 time for the bfm memory issue.  
[working_bfm_ddr3_mem_issue.zip](https://github.com/OPAE/opae-sdk/files/2236220/working_bfm_ddr3_mem_issue.zip)

**Comment by deepakcu84** [comment]
sorry, was caught up with various release issues. havent' had time to look at this one. I'll have an update next week.

**Comment by tswhison** [comment]
Hi Deepak, any update on this one?  Thanks

**Comment by tswhison** [comment]
Closing as no traffic.
